
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU AGPL 3.0"
[[mods]] #mandatory
modId="botapi" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Bot-Connect" #mandatory
logoFile="assets/botapi/icon.png" #optional
authors="cnlimiter" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds chat linking between QQ and Minecraft and QQ commands to request server data.
'''
[[dependencies.botapi]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory
ordering="NONE"
side="BOTH"

